import { PERMISSIONS } from '../../core/auth/permissions';


export const PROJECT_PERMISSIONS = {

  READ: PERMISSIONS.PROJECT.READ,

  CREATE: PERMISSIONS.PROJECT.CREATE,

  UPDATE: PERMISSIONS.PROJECT.UPDATE,

  DELETE: PERMISSIONS.PROJECT.DELETE,

} as const;